// Generated by CoffeeScript 1.4.0
var WebFontConfig;

WebFontConfig = {
  google: {
    families: ['Lobster', 'Dancing Script', 'Josefin Slab', 'Abril Fatface', 'Vollkorn', 'Hammersmith One', 'Orbitron', 'Atomic Age', 'Quicksand', 'VT323', 'Special Elite', 'Miltonian', 'Changa One', 'Passion One', 'Codystar', 'Astloch', 'Tangerine', 'Stardos Stencil', 'Skranji', 'Oleo Script', 'New Rocker', 'Keania One', 'Text Me One', 'Hanalei', 'Anaheim', 'Norican', 'Unica One', 'Archivo Black', 'Londrina Solid', 'Chela One', 'Arbutus', 'Rye', 'Bilbo Swash Caps', 'Titan One', 'Raleway Dots', 'Sancreek', 'Bowlby One', 'Bigshot One', 'Smokum', 'Monoton', 'Poiret One', 'Spicy Rice', 'Anton', 'Alfa Slab One', 'Economica', 'Abril Fatface', 'Wallpoet', 'UnifrakturMaguntia', 'Luckiest Guy', 'Rouge Script', 'Paytone One', 'Ultra', 'Creepster']
  },
  loading: function() {
    return $('<div id="loading">').css({
      position: 'absolute',
      display: 'none',
      height: '100px',
      width: '500px',
      top: Math.floor(($(window).height() - 100) / 2),
      left: Math.floor(($(window).width() - 500) / 2),
      'text-align': 'center',
      'font-family': 'Arial'
    }).html('FizzBuzz').appendTo($('body')).fadeIn((function() {
      return $('#loading').delay(2000).fadeOut((function() {
        return $('#loading').html('by Kazuya Takahashi').fadeIn((function() {
          return $('#loading').delay(3000).fadeOut();
        }));
      }));
    }));
  },
  active: function() {
    var fizzbuzz, i, num, run;
    fizzbuzz = new FizzBuzz(new Browser);
    num = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 1000; i = ++_i) {
        _results.push(i);
      }
      return _results;
    })();
    run = function() {
      if (num.length === 0) {
        return;
      }
      fizzbuzz.say(num[0]);
      num.shift();
      return setTimeout((function() {
        return run();
      }), 100);
    };
    return run();
  }
};

(function() {
  var s, wf;
  wf = document.createElement('script');
  wf.src = ('https:' === document.location.protocol ? 'https' : 'http') + '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';
  s = document.getElementsByTagName('script')[0];
  return s.parentNode.insertBefore(wf, s);
})();
