// Generated by CoffeeScript 1.4.0
var FizzBuzz, exports;

FizzBuzz = (function() {

  function FizzBuzz(output) {
    this.output = output;
  }

  FizzBuzz.prototype.say = function(num) {
    return this.output.display(String(this._say(num)));
  };

  FizzBuzz.prototype._say = function(num) {
    if (num % (3 * 5) === 0) {
      return 'FizzBuzz';
    }
    if (num % 3 === 0) {
      return 'Fizz';
    }
    if (num % 5 === 0) {
      return 'Buzz';
    }
    return num;
  };

  return FizzBuzz;

})();

if (!exports) {
  exports = {};
}

exports.FizzBuzz = FizzBuzz;
